# Generated by Django 2.0.8 on 2018-09-01 19:11

import datetime
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.CharField(max_length=30)),
                ('issued_by', models.CharField(max_length=30)),
                ('current_status', models.BooleanField(default=True)),
                ('reissues', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)])),
                ('issued_date', models.DateField(default=datetime.datetime(2018, 9, 2, 0, 41, 25, 301482))),
                ('returned_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libId', models.CharField(max_length=30)),
                ('lib_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=10)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
