# Generated by Django 2.0.8 on 2018-09-01 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0004_auto_20180902_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 22, 15, 25, 583167, tzinfo=utc)),
        ),
    ]
