# Generated by Django 2.0.8 on 2018-09-02 05:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0017_auto_20180902_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='issued_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 2, 5, 23, 8, 493271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='returned_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 2, 10, 53, 8, 493271)),
        ),
    ]
