# Generated by Django 2.0.8 on 2018-09-02 05:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0019_auto_20180902_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 5, 28, 48, 396712, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 10, 58, 48, 396712)),
        ),
    ]
